
write2arl



Examples
```{r}
write2arl("microsat_test", microsat_data, "MICROSAT", 3, "0")
write2arl("SNP_test", snp_data, "STANDARD", 3, "-9")
write2arl("mtDNA_test", mtdna_data, "DNA", 3, "?")
```


Run this first
```{r}
write2arl<- function(title, df, ut, np, md){
  
  
  if (ut == "MICROSAT"){
      
    gd=1
  
    frames2 <- split(df, df[,2], drop = FALSE) #split new df by reg

    reg.names<- as.vector(df[,2]) #get region names
    reg.names2<- unique(unlist(reg.names, use.names=TRUE)) #keep unique regions
    reg.names3<- sort(reg.names2) #sort alphabetically
  
    fileConn<- file(sprintf("%s.arp", title), "wt")
    writeLines('[Profile]', fileConn)
    cat('\n', file=fileConn)
    cat('Title="', title, sep ="", file=fileConn)
    cat('"', file=fileConn)
    cat('\n', file=fileConn)
    cat('NbSamples=', np, sep="", file=fileConn) #input num pops
    cat('\n', file=fileConn)
    cat('DataType=', ut, sep="", file=fileConn) #input ut
    cat('\n', file=fileConn)
    cat('GenotypicData=', gd, sep="", file=fileConn) #input ploidy
    cat('\n', file=fileConn)
    writeLines('GameticPhase=0', fileConn)
    writeLines('LocusSeparator=TAB', fileConn) #what to use as locus separator?
    cat('MissingData="', md, sep="", file=fileConn)
    cat('"', file=fileConn)
    cat('\n', file=fileConn)
    cat('\n', file=fileConn)
    writeLines('[Data]', fileConn)
    cat('\n', file=fileConn)
    writeLines('[[Samples]]', fileConn)
    cat('\n', file=fileConn)
    close(fileConn)

    i=1

    for (frame2 in frames2){ #for each region
      a1<- data.frame(frame2[seq(3,ncol(frame2),2)]) #make df for allele 1
      a1.1<- as.data.frame(append(a1,1,after=0)) #add column of 1's
      a1.2<- cbind(frame2[1], a1.1) #add sample names
      a2<- data.frame(frame2[seq(4,ncol(frame2),2)]) #make df for allele 2
      a2.1<- as.data.frame(append(a2,"",after=0)) #add blank column in front
      a2.2<- as.data.frame(append(a2.1,"",after=0)) #add blank column in front
      colnames(a2.2)<- colnames(a1.2) #match column names
      aa1<- data.frame(lapply(a1.2, as.character), stringsAsFactors = FALSE) 
      aa2<- data.frame(lapply(a2.2, as.character), stringsAsFactors = FALSE)
      afinal<- bind_rows(aa1,aa2) #combine df for each allele
      afinal2<- afinal[kronecker(1:nrow(aa1), c(0,nrow(aa1)), "+"), ] #reorder rows

      fileConn<- file(sprintf("%s.arp", title), "at")
      cat('SampleName="', as.character(reg.names3[i]), sep="", file=fileConn)
      cat('"', file=fileConn)
      cat('\n', file=fileConn)
      cat('SampleSize= ', nrow(frame2), sep="", file=fileConn)
      cat('\n', file=fileConn)
      writeLines('SampleData= {', fileConn)
      cat('\n', file=fileConn)
      write.table(afinal2, file = fileConn, quote = FALSE, sep = "\t", na = "", row.names = FALSE, col.names = FALSE)
      writeLines('}', fileConn)
      cat('\n', file=fileConn)
      close(fileConn)
      i=i+1
    }

    fileConn<- file(sprintf("%s.arp", title), "at")
    writeLines('[[Structure]]', fileConn)
    writeLines('StructureName=""', fileConn)
    writeLines('NbGroups=1', fileConn)
    writeLines('Group={', fileConn)
    close(fileConn)

    for (name in reg.names3){
      fileConn<- file(sprintf("%s.arp", title), "at")
      cat('\t"', name, sep="", file=fileConn)
      cat('"', file=fileConn)
      cat('\n', file=fileConn)
      close(fileConn)
    }

    fileConn<- file(sprintf("%s.arp", title), "at")
    writeLines('}', fileConn)
    close(fileConn)

}
  
  else if (ut == "STANDARD"){
    
    df[df=="TRUE"]<- "T" #replaces TRUE(from import) with T

    gd=1
  
    frames2 <- split(df, df[,2], drop = FALSE) #split new df by reg

    reg.names<- as.vector(df[,2]) #get region names
    reg.names2<- unique(unlist(reg.names, use.names=TRUE)) #keep unique regions
    reg.names3<- sort(reg.names2) #sort alphabetically
  
    fileConn<- file(sprintf("%s.arp", title), "wt")
    writeLines('[Profile]', fileConn)
    cat('\n', file=fileConn)
    cat('Title="', title, sep ="", file=fileConn)
    cat('"', file=fileConn)
    cat('\n', file=fileConn)
    cat('NbSamples=', np, sep="", file=fileConn) #input num pops
    cat('\n', file=fileConn)
    cat('DataType=', ut, sep="", file=fileConn) #input ut
    cat('\n', file=fileConn)
    cat('GenotypicData=', gd, sep="", file=fileConn) #input ploidy
    cat('\n', file=fileConn)
    writeLines('GameticPhase=0', fileConn)
    writeLines('LocusSeparator=TAB', fileConn) #what to use as locus separator?
    cat('MissingData="', md, sep="", file=fileConn)
    cat('"', file=fileConn)
    cat('\n', file=fileConn)
    cat('\n', file=fileConn)
    writeLines('[Data]', fileConn)
    cat('\n', file=fileConn)
    writeLines('[[Samples]]', fileConn)
    cat('\n', file=fileConn)
    close(fileConn)

    i=1

    for (frame2 in frames2){ #for each region
      a1<- data.frame(frame2[seq(3,ncol(frame2),2)]) #make df for allele 1
      a1.1<- as.data.frame(append(a1,1,after=0)) #add column of 1's
      a1.2<- cbind(frame2[1], a1.1) #add sample names
      a2<- data.frame(frame2[seq(4,ncol(frame2),2)]) #make df for allele 2
      a2.1<- as.data.frame(append(a2,"",after=0)) #add blank column in front
      a2.2<- as.data.frame(append(a2.1,"",after=0)) #add blank column in front
      colnames(a2.2)<- colnames(a1.2) #match column names
      aa1<- data.frame(lapply(a1.2, as.character), stringsAsFactors = FALSE) 
      aa2<- data.frame(lapply(a2.2, as.character), stringsAsFactors = FALSE)
      afinal<- bind_rows(aa1,aa2) #combine df for each allele
      afinal2<- afinal[kronecker(1:nrow(aa1), c(0,nrow(aa1)), "+"), ] #reorder rows

      fileConn<- file(sprintf("%s.arp", title), "at")
      cat('SampleName="', as.character(reg.names3[i]), sep="", file=fileConn)
      cat('"', file=fileConn)
      cat('\n', file=fileConn)
      cat('SampleSize= ', nrow(frame2), sep="", file=fileConn)
      cat('\n', file=fileConn)
      writeLines('SampleData= {', fileConn)
      cat('\n', file=fileConn)
      write.table(afinal2, file = fileConn, quote = FALSE, sep = "\t", na = "", row.names = FALSE, col.names = FALSE)
      writeLines('}', fileConn)
      cat('\n', file=fileConn)
      close(fileConn)
      i=i+1
    }

    fileConn<- file(sprintf("%s.arp", title), "at")
    writeLines('[[Structure]]', fileConn)
    writeLines('StructureName=""', fileConn)
    writeLines('NbGroups=1', fileConn)
    writeLines('Group={', fileConn)
    close(fileConn)

    for (name in reg.names3){
      fileConn<- file(sprintf("%s.arp", title), "at")
      cat('\t"', name, sep="", file=fileConn)
      cat('"', file=fileConn)
      cat('\n', file=fileConn)
      close(fileConn)
    }

    fileConn<- file(sprintf("%s.arp", title), "at")
    writeLines('}', fileConn)
    close(fileConn)

  }  
    
  else if (ut == "DNA"){
    
    gd=0
  
    frames2 <- split(df, df[,2], drop = FALSE) #split new df by reg

    reg.names<- as.vector(df[,2]) #get region names
    reg.names2<- unique(unlist(reg.names, use.names=TRUE)) #keep unique regions
    reg.names3<- sort(reg.names2) #sort alphabetically
    reg.names4<- append(reg.names3, "blank", after=0) #to be used in parsing
  
  
    fileConn<- file(sprintf("%s.arp", title), "wt")
    writeLines('[Profile]', fileConn)
    cat('\n', file=fileConn)
    cat('Title="', title, sep ="", file=fileConn)
    cat('"', file=fileConn)
    cat('\n', file=fileConn)
    cat('NbSamples=', np, sep="", file=fileConn) #input num pops
    cat('\n', file=fileConn)
    cat('DataType=', ut, sep="", file=fileConn) #input ut
    cat('\n', file=fileConn)
    cat('GenotypicData=', gd, sep="", file=fileConn) #input ploidy
    cat('\n', file=fileConn)
    writeLines('GameticPhase=0', fileConn)
    writeLines('LocusSeparator=TAB', fileConn) #what to use as locus separator?
    cat('MissingData="', md, sep="", file=fileConn)
    cat('"', file=fileConn)
    cat('\n', file=fileConn)
    cat('\n', file=fileConn)
    writeLines('[Data]', fileConn)
    cat('\n', file=fileConn)
    writeLines('[[Samples]]', fileConn)
    cat('\n', file=fileConn)
    close(fileConn)

    i=1

    for (frame2 in frames2){ #for each region
      a1<- data.frame(frame2[seq(3,ncol(frame2),2)]) #make df for allele 1
      a1.1<- as.data.frame(append(a1,1,after=0)) #add column of 1's
      a1.2<- cbind(frame2[1], a1.1) #add sample names
      aa1<- data.frame(lapply(a1.2, as.character), stringsAsFactors = FALSE) 
  
      fileConn<- file(sprintf("%s.arp", title), "at")
      cat('SampleName="', as.character(reg.names3[i]), sep="", file=fileConn)
      cat('"', file=fileConn)
      cat('\n', file=fileConn)
      cat('SampleSize= ', nrow(frame2), sep="", file=fileConn)
      cat('\n', file=fileConn)
      writeLines('SampleData= {', fileConn)
      cat('\n', file=fileConn)
      write.table(aa1, file = fileConn, quote = FALSE, sep = "\t", na = "", row.names = FALSE, col.names = FALSE)
      writeLines('}', fileConn)
      cat('\n', file=fileConn)
      close(fileConn)
      i=i+1
    }

    fileConn<- file(sprintf("%s.arp", title), "at")
    writeLines('[[Structure]]', fileConn)
    writeLines('StructureName=""', fileConn)
    writeLines('NbGroups=1', fileConn)
    writeLines('Group={', fileConn)
    close(fileConn)

    for (name in reg.names3){
      fileConn<- file(sprintf("%s.arp", title), "at")
      cat('\t"', name, sep="", file=fileConn)
      cat('"', file=fileConn)
      cat('\n', file=fileConn)
      close(fileConn)
    }

    fileConn<- file(sprintf("%s.arp", title), "at")
    writeLines('}', fileConn)
    close(fileConn) 
    
    
  }  
  
  else {
    print("ERROR, marker type must be (MICROSAT, STANDARD, or DNA)")
    
  }
  
}
```

